/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeUserPasswordRequest
 */
export interface ChangeUserPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof ChangeUserPasswordRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeUserPasswordRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the ChangeUserPasswordRequest interface.
 */
export function instanceOfChangeUserPasswordRequest(value: object): value is ChangeUserPasswordRequest {
    return true;
}

export function ChangeUserPasswordRequestFromJSON(json: any): ChangeUserPasswordRequest {
    return ChangeUserPasswordRequestFromJSONTyped(json, false);
}

export function ChangeUserPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeUserPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function ChangeUserPasswordRequestToJSON(json: any): ChangeUserPasswordRequest {
    return ChangeUserPasswordRequestToJSONTyped(json, false);
}

export function ChangeUserPasswordRequestToJSONTyped(value?: ChangeUserPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

