/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFormRequest
 */
export interface CreateFormRequest {
    /**
     * 
     * @type {boolean}
     * @memberof CreateFormRequest
     */
    published?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateFormRequest
     */
    formTemplateIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFormRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the CreateFormRequest interface.
 */
export function instanceOfCreateFormRequest(value: object): value is CreateFormRequest {
    return true;
}

export function CreateFormRequestFromJSON(json: any): CreateFormRequest {
    return CreateFormRequestFromJSONTyped(json, false);
}

export function CreateFormRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFormRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'published': json['published'] == null ? undefined : json['published'],
        'formTemplateIdentifier': json['formTemplateIdentifier'] == null ? undefined : json['formTemplateIdentifier'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function CreateFormRequestToJSON(json: any): CreateFormRequest {
    return CreateFormRequestToJSONTyped(json, false);
}

export function CreateFormRequestToJSONTyped(value?: CreateFormRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'published': value['published'],
        'formTemplateIdentifier': value['formTemplateIdentifier'],
        'username': value['username'],
    };
}

