/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFormTemplateContentRequest
 */
export interface CreateFormTemplateContentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateFormTemplateContentRequest
     */
    contentName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFormTemplateContentRequest
     */
    contentType?: string;
}

/**
 * Check if a given object implements the CreateFormTemplateContentRequest interface.
 */
export function instanceOfCreateFormTemplateContentRequest(value: object): value is CreateFormTemplateContentRequest {
    return true;
}

export function CreateFormTemplateContentRequestFromJSON(json: any): CreateFormTemplateContentRequest {
    return CreateFormTemplateContentRequestFromJSONTyped(json, false);
}

export function CreateFormTemplateContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFormTemplateContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contentName': json['contentName'] == null ? undefined : json['contentName'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
    };
}

export function CreateFormTemplateContentRequestToJSON(json: any): CreateFormTemplateContentRequest {
    return CreateFormTemplateContentRequestToJSONTyped(json, false);
}

export function CreateFormTemplateContentRequestToJSONTyped(value?: CreateFormTemplateContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contentName': value['contentName'],
        'contentType': value['contentType'],
    };
}

