/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFormTemplateSignatureRequest
 */
export interface CreateFormTemplateSignatureRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateFormTemplateSignatureRequest
     */
    level?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateFormTemplateSignatureRequest
     */
    title?: string;
}

/**
 * Check if a given object implements the CreateFormTemplateSignatureRequest interface.
 */
export function instanceOfCreateFormTemplateSignatureRequest(value: object): value is CreateFormTemplateSignatureRequest {
    return true;
}

export function CreateFormTemplateSignatureRequestFromJSON(json: any): CreateFormTemplateSignatureRequest {
    return CreateFormTemplateSignatureRequestFromJSONTyped(json, false);
}

export function CreateFormTemplateSignatureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFormTemplateSignatureRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'] == null ? undefined : json['level'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function CreateFormTemplateSignatureRequestToJSON(json: any): CreateFormTemplateSignatureRequest {
    return CreateFormTemplateSignatureRequestToJSONTyped(json, false);
}

export function CreateFormTemplateSignatureRequestToJSONTyped(value?: CreateFormTemplateSignatureRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'title': value['title'],
    };
}

