/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFormTemplateContentRequest } from './CreateFormTemplateContentRequest';
import {
    CreateFormTemplateContentRequestFromJSON,
    CreateFormTemplateContentRequestFromJSONTyped,
    CreateFormTemplateContentRequestToJSON,
    CreateFormTemplateContentRequestToJSONTyped,
} from './CreateFormTemplateContentRequest';
import type { CreateFormTemplateSignatureRequest } from './CreateFormTemplateSignatureRequest';
import {
    CreateFormTemplateSignatureRequestFromJSON,
    CreateFormTemplateSignatureRequestFromJSONTyped,
    CreateFormTemplateSignatureRequestToJSON,
    CreateFormTemplateSignatureRequestToJSONTyped,
} from './CreateFormTemplateSignatureRequest';

/**
 * 
 * @export
 * @interface CreateFormTemplateRequest
 */
export interface CreateFormTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateFormTemplateRequest
     */
    formTemplateIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFormTemplateRequest
     */
    formTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFormTemplateRequest
     */
    formDescription?: string;
    /**
     * 
     * @type {Array<CreateFormTemplateContentRequest>}
     * @memberof CreateFormTemplateRequest
     */
    formTemplateContents?: Array<CreateFormTemplateContentRequest>;
    /**
     * 
     * @type {Array<CreateFormTemplateSignatureRequest>}
     * @memberof CreateFormTemplateRequest
     */
    formTemplateSignatures?: Array<CreateFormTemplateSignatureRequest>;
}

/**
 * Check if a given object implements the CreateFormTemplateRequest interface.
 */
export function instanceOfCreateFormTemplateRequest(value: object): value is CreateFormTemplateRequest {
    return true;
}

export function CreateFormTemplateRequestFromJSON(json: any): CreateFormTemplateRequest {
    return CreateFormTemplateRequestFromJSONTyped(json, false);
}

export function CreateFormTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFormTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'formTemplateIdentifier': json['formTemplateIdentifier'] == null ? undefined : json['formTemplateIdentifier'],
        'formTitle': json['formTitle'] == null ? undefined : json['formTitle'],
        'formDescription': json['formDescription'] == null ? undefined : json['formDescription'],
        'formTemplateContents': json['formTemplateContents'] == null ? undefined : ((json['formTemplateContents'] as Array<any>).map(CreateFormTemplateContentRequestFromJSON)),
        'formTemplateSignatures': json['formTemplateSignatures'] == null ? undefined : ((json['formTemplateSignatures'] as Array<any>).map(CreateFormTemplateSignatureRequestFromJSON)),
    };
}

export function CreateFormTemplateRequestToJSON(json: any): CreateFormTemplateRequest {
    return CreateFormTemplateRequestToJSONTyped(json, false);
}

export function CreateFormTemplateRequestToJSONTyped(value?: CreateFormTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'formTemplateIdentifier': value['formTemplateIdentifier'],
        'formTitle': value['formTitle'],
        'formDescription': value['formDescription'],
        'formTemplateContents': value['formTemplateContents'] == null ? undefined : ((value['formTemplateContents'] as Array<any>).map(CreateFormTemplateContentRequestToJSON)),
        'formTemplateSignatures': value['formTemplateSignatures'] == null ? undefined : ((value['formTemplateSignatures'] as Array<any>).map(CreateFormTemplateSignatureRequestToJSON)),
    };
}

