/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchFormRequest
 */
export interface SearchFormRequest {
    /**
     * 
     * @type {number}
     * @memberof SearchFormRequest
     */
    formId?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchFormRequest
     */
    formTemplateIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchFormRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the SearchFormRequest interface.
 */
export function instanceOfSearchFormRequest(value: object): value is SearchFormRequest {
    return true;
}

export function SearchFormRequestFromJSON(json: any): SearchFormRequest {
    return SearchFormRequestFromJSONTyped(json, false);
}

export function SearchFormRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchFormRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'formId': json['formId'] == null ? undefined : json['formId'],
        'formTemplateIdentifier': json['formTemplateIdentifier'] == null ? undefined : json['formTemplateIdentifier'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function SearchFormRequestToJSON(json: any): SearchFormRequest {
    return SearchFormRequestToJSONTyped(json, false);
}

export function SearchFormRequestToJSONTyped(value?: SearchFormRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'formId': value['formId'],
        'formTemplateIdentifier': value['formTemplateIdentifier'],
        'username': value['username'],
    };
}

