/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignFormRequest
 */
export interface SignFormRequest {
    /**
     * 
     * @type {number}
     * @memberof SignFormRequest
     */
    formId?: number;
    /**
     * 
     * @type {string}
     * @memberof SignFormRequest
     */
    username?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SignFormRequest
     */
    approved?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SignFormRequest
     */
    denialReason?: string;
}

/**
 * Check if a given object implements the SignFormRequest interface.
 */
export function instanceOfSignFormRequest(value: object): value is SignFormRequest {
    return true;
}

export function SignFormRequestFromJSON(json: any): SignFormRequest {
    return SignFormRequestFromJSONTyped(json, false);
}

export function SignFormRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignFormRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'formId': json['formId'] == null ? undefined : json['formId'],
        'username': json['username'] == null ? undefined : json['username'],
        'approved': json['approved'] == null ? undefined : json['approved'],
        'denialReason': json['denialReason'] == null ? undefined : json['denialReason'],
    };
}

export function SignFormRequestToJSON(json: any): SignFormRequest {
    return SignFormRequestToJSONTyped(json, false);
}

export function SignFormRequestToJSONTyped(value?: SignFormRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'formId': value['formId'],
        'username': value['username'],
        'approved': value['approved'],
        'denialReason': value['denialReason'],
    };
}

