/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFormContentRequest
 */
export interface UpdateFormContentRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateFormContentRequest
     */
    formContentId?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateFormContentRequest
     */
    contentData?: string;
}

/**
 * Check if a given object implements the UpdateFormContentRequest interface.
 */
export function instanceOfUpdateFormContentRequest(value: object): value is UpdateFormContentRequest {
    return true;
}

export function UpdateFormContentRequestFromJSON(json: any): UpdateFormContentRequest {
    return UpdateFormContentRequestFromJSONTyped(json, false);
}

export function UpdateFormContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFormContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'formContentId': json['formContentId'] == null ? undefined : json['formContentId'],
        'contentData': json['contentData'] == null ? undefined : json['contentData'],
    };
}

export function UpdateFormContentRequestToJSON(json: any): UpdateFormContentRequest {
    return UpdateFormContentRequestToJSONTyped(json, false);
}

export function UpdateFormContentRequestToJSONTyped(value?: UpdateFormContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'formContentId': value['formContentId'],
        'contentData': value['contentData'],
    };
}

